### ISSUE TITLE
1.1 images should warmup the cache with netcoreapp1.1 packages

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/dotnet-docker-nightly#116]
Currently, 1.1-sdk-**msbuild** images [perform a nuget cache warmup](https://github.com/dotnet/dotnet-docker-nightly/blob/1edc6a01691b15e0bff6d8b2d7be5f8f97bee780/1.1/debian/sdk/msbuild/Dockerfile#L39), however, this warmup does not include packages that are new to netcoreapp1.1. 

This leads to restore errors when building inside the sdk image:
```
Unable to resolve 'Microsoft.NETCore.Runtime.CoreCLR (>= 1.1.0)' for '.NETCoreApp,Version=v1.1'.
```

cc @MichaelSimons @naamunds

**Comment by MichaelSimons** [comment]
@natemcmaster, This is somewhat expected behavior because CLI does not have support for specifying a target runtime.  This is something that will supposedly be added before RTM.  Because 1.1 hasn't released, you need to specify a custom NuGet.config for the time being.  Once 1.1 is released, the packages will get resolved automatically although will not be pre-cached locally.  We could pre-populate the cache manually if needed.

@richlander  - thoughts?

**Comment by natemcmaster** [comment]
FWIW **1.1.0-sdk-projectjson** image has the 1.1.0 packages in the nuget cache, but **1.1.0-sdk-msbuild** does not.

**Comment by MichaelSimons** [comment]
@natemcmaster - That is because the 1.1.0-sdk-projectjson image installs the preview 2.1 sdk which is based on 1.1 runtime.  The 1.1.0-sdk-msbuild image is based on preview3 sdk which is based on 1.0.1 runtime.  The built in sdk cache population logic is based on the runtime the sdk targets not what runtime the user would like to target.

**Comment by natemcmaster** [comment]
> The built in sdk cache population logic is based on the runtime the sdk targets not what runtime the user would like to target

That's the wrong assumption. If I've chosen the **1.1.0-sdk-msbuild** image instead of **1.0.0-sdk-msbuild**, it's because I'm trying to target the 1.1 runtime, not 1.0.

**Comment by MichaelSimons** [comment]
@natemcmaster, I am not disagreeing.  I am pointing out that this is a missing feature with the CLI's package initialization logic.  In this case is it not only wrong to not have the 1.1 packages, it is also wrong/wasteful to pull all of the 1.0.1 packages if the user will never use them.  @richlander, has said that the CLI needs to provide the ability for users to specify a target runtime.  This should include building the appropriate package cache.

**Comment by natemcmaster** [comment]
Makes sense. And I agree with you -- this is a missing feature of the SDK first run experience and dotnet-new.
But in the meantime, could the image still work around this? i.e. opt-out of SDK's first-run package initialization and do a cache warmup using 1.1 dependencies?

**Comment by MichaelSimons** [comment]
This is certainly possible.  CLI checks an env var to see if the first run experience should be performed.  We can set that env var appropriately and then can `dotnet new`, change the target runtime, and then `dotnet restore`.
